spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/evrensesi
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

