spring:
  application:
    name: evrensesi

  profiles:
    active: prod

  messages:
    basename: ExceptionMessages,ValidationMessages
    encoding: UTF-8

server:
  port: 8080

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: never